/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://ivzpq3eqpzbptdzcdozzagqgsa.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-62qtf4sqdjcv5latbu7f44bkzq",
    "aws_cognito_identity_pool_id": "eu-central-1:0b97878f-72b5-4145-b269-45cde20928c6",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_uLS0E5v9D",
    "aws_user_pools_web_client_id": "73sjjomdfdbj6bnqqdppmfsbac",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "photos110954-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
