/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://kbthqgke5vd3nphfh6eubt4vme.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gwuwgas7cvae5nt5dmixmc5hpm",
    "aws_cognito_identity_pool_id": "eu-central-1:e8c10662-26e2-41ef-b0ae-fc5e4237f00f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_unCm7mCvJ",
    "aws_user_pools_web_client_id": "4b7vrn1bnbqd4q95r6k712vpio",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "photos111739-main",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;

